### PR TITLE
Siteicon-design-by-sowmiya

### LINKED ISSUE #7: Create site icon
We must define a icon for the site!

This is a site for trading album stickers, specially for the FIFA World Cup Panini sticker album.

Feel free to improve as you want!

### PR DESCRIPTION
**Pull request by sowmiyeh**
Description
This PR adds one new logo for this repo.

Related Issue
Closes #7 

Acceptance Criteria
- [x] File Formats: SVG
- [x]   Sizes of 16x16, 32x32, 96x96,180x180

Logo Description

Figma Link - https://www.figma.com/file/EFydR0MFVlKw22HLcMlN5t/Trading-album-stickers?node-id=1%3A44

### CODE REVIEW

**Comment by sowmiyeh** [comment]
Hi @dcbCIn Please, Check and Merge it, Thanks!

**Comment by dcruzb** [comment]
Cool! I liked the references! Thanks for the contribution!

**Comment by dcruzb** [comment]
@all-contributors please add @sowmiya-venkatesan for design

**Comment by sowmiyeh** [comment]
> Cool! I liked the references! Thanks for the contribution!

Thank you @dcbCIn

**Pull request merged**
