### PR TITLE
Add contributing.md guide

### LINKED ISSUE #1: Add contributing guide
A simple and welcoming CONTRIBUTING.md file to help new contributors.

### LINKED ISSUE #14: Adjust contributing guide as contributing.md file
Enhance the contributing guide.

### PR DESCRIPTION
**Pull request by dcruzb**
Closes #14

### CODE REVIEW

**Comment by dcbCIn** [comment]
@all-contributors please add @dcb for docs

**Comment by dcbCIn** [comment]
https://github.com/all-contributors please add @dcbCIn  for docs

**Comment by dcbCIn** [comment]
@all-contributors please add @dcb for docs

**Comment by dcruzb** [comment]
@all-contributors please add @dcbCIn for docs

**Pull request merged**
